site_name: Latisha
theme:
    name: material
    font:
       text: LXGW WenKai Mono TC
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.path
        - navigation.sections
        - navigation.top
nav:
   - Home: index.md
   - Getting started: 
      - [Bootstrap table](/blog/posts/Bootstrap-table.md)
      - [log](/blog/posts/log.md)
      - [XSS 處理](/blog/posts/XSS 處理.md)
plugins:
    - search
    - blog
  #  - literate-nav:
     #   nav_file: SUMMARY.md
