site_name: Latisha
site_description: >-
  主要 for 自我回顧好抄(咦) 
  可能有的：coding、翻譯、my 娛樂用、雜七雜八不知道
  
# Repository
repo_name: Latisha19/Latisha19.github.io
repo_url: https://github.com/Latisha19/Latisha19.github.io

# Copyright
copyright: Copyright &copy; 2023 - 2025 Latisha^^

theme:
    name: material
    font:
       text: LXGW WenKai Mono TC
    features:
        # - navigation.tabs
        # - navigation.tabs.sticky
        # - navigation.path
        # - navigation.sections
        # - navigation.top
        # - navigation.instant
        # - navigation.instant.progress
        # - navigation.indexes 
        # - toc.follow
        - announce.dismiss
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
nav:
   - Home: index.md
   - Blogs: # blog/
        - blog/index.md
        - blog/posts/
plugins:
    - search
    - blog:
        pagination: true
        pagination_per_page: 5
        pagination_if_single_page: true
        pagination_keep_content: false
    # - literate-nav:
        # nav_file: SUMMARY.md
        
markdown_extensions:
  - admonition