site_name: Latisha

# Repository
repo_name: Latisha19/Latisha19.github.io
repo_url: https://github.com/Latisha19/Latisha19.github.io

# Copyright
copyright: Copyright &copy; 2023 - 2025 Latisha^^

theme:
    name: material
    font:
       text: LXGW WenKai Mono TC
    features:
        # - navigation.tabs
        # - navigation.tabs.sticky
        # - navigation.path
        # - navigation.sections
        # - navigation.top
        # - navigation.instant
        # - navigation.instant.progress
        # - navigation.indexes 
        # - toc.follow
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
nav:
   - Home: index.md
   - Blogs: 
        - blog/index.md
plugins:
    - search
    - blog:
        pagination: true
        pagination_per_page: 5
        pagination_if_single_page: true
        pagination_keep_content: false
  #  - literate-nav:
     #   nav_file: SUMMARY.md