site_name: Latisha
theme:
    name: material
    font:
       text: LXGW WenKai Mono TC
    features:
        # - navigation.tabs
        # - navigation.tabs.sticky
        # - navigation.path
        # - navigation.sections
        # - navigation.top
        # - navigation.instant
        # - navigation.instant.progress
        # - navigation.indexes 
        # - toc.follow
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
nav:
   - Home: index.md
   - Blogs: 
        - blog/index.md
        - Bootstrap table: blog/Bootstrap-table.md
        - log: blog/log.md
        - XSS 處理: blog/XSS 處理.md
plugins:
    - search
    - blog
  #  - literate-nav:
     #   nav_file: SUMMARY.md